# Combined Deployment and Service manifest for your app
# -----------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1   # You can increase this later for scaling
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: varunv25/myapp:latest   # ✅ Your Docker Hub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8888        # ✅ Match this with your app’s exposed port
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 8888  # Internal app port
  type: NodePort        # ✅ Ideal for Minikube; use LoadBalancer + 'minikube tunnel' if desired
